/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.generation2.tables.records;


import edu.java.domain.jooq.generation2.tables.Link;

import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINK.LINK_NAME</code>.
     */
    public void setLinkName(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK.LINK_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000)
    @NotNull
    public String getLinkName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINK.LAST_CHECK</code>.
     */
    public void setLastCheck(@Nullable LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINK.LAST_CHECK</code>.
     */
    @Nullable
    public LocalDateTime getLastCheck() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>LINK.LAST_UPDATE</code>.
     */
    public void setLastUpdate(@Nullable LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINK.LAST_UPDATE</code>.
     */
    @Nullable
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>LINK.LAST_COMMIT</code>.
     */
    public void setLastCommit(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINK.LAST_COMMIT</code>.
     */
    @Nullable
    public LocalDateTime getLastCommit() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>LINK.AMOUNT_ISSUES</code>.
     */
    public void setAmountIssues(@Nullable Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>LINK.AMOUNT_ISSUES</code>.
     */
    @Nullable
    public Integer getAmountIssues() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>LINK.TYPE</code>.
     */
    public void setType(@Nullable String value) {
        set(6, value);
    }

    /**
     * Getter for <code>LINK.TYPE</code>.
     */
    @Size(max = 31)
    @Nullable
    public String getType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row7<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.LINK_NAME;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field3() {
        return Link.LINK.LAST_CHECK;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field4() {
        return Link.LINK.LAST_UPDATE;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return Link.LINK.LAST_COMMIT;
    }

    @Override
    @NotNull
    public Field<Integer> field6() {
        return Link.LINK.AMOUNT_ISSUES;
    }

    @Override
    @NotNull
    public Field<String> field7() {
        return Link.LINK.TYPE;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getLinkName();
    }

    @Override
    @Nullable
    public LocalDateTime component3() {
        return getLastCheck();
    }

    @Override
    @Nullable
    public LocalDateTime component4() {
        return getLastUpdate();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getLastCommit();
    }

    @Override
    @Nullable
    public Integer component6() {
        return getAmountIssues();
    }

    @Override
    @Nullable
    public String component7() {
        return getType();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getLinkName();
    }

    @Override
    @Nullable
    public LocalDateTime value3() {
        return getLastCheck();
    }

    @Override
    @Nullable
    public LocalDateTime value4() {
        return getLastUpdate();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getLastCommit();
    }

    @Override
    @Nullable
    public Integer value6() {
        return getAmountIssues();
    }

    @Override
    @Nullable
    public String value7() {
        return getType();
    }

    @Override
    @NotNull
    public LinkRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@NotNull String value) {
        setLinkName(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@Nullable LocalDateTime value) {
        setLastCheck(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@Nullable LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value5(@Nullable LocalDateTime value) {
        setLastCommit(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value6(@Nullable Integer value) {
        setAmountIssues(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value7(@Nullable String value) {
        setType(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(@Nullable Long value1, @NotNull String value2, @Nullable LocalDateTime value3, @Nullable LocalDateTime value4, @Nullable LocalDateTime value5, @Nullable Integer value6, @Nullable String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({ "id", "linkName", "lastCheck", "lastUpdate", "lastCommit", "amountIssues", "type" })
    public LinkRecord(@Nullable Long id, @NotNull String linkName, @Nullable LocalDateTime lastCheck, @Nullable LocalDateTime lastUpdate, @Nullable LocalDateTime lastCommit, @Nullable Integer amountIssues, @Nullable String type) {
        super(Link.LINK);

        setId(id);
        setLinkName(linkName);
        setLastCheck(lastCheck);
        setLastUpdate(lastUpdate);
        setLastCommit(lastCommit);
        setAmountIssues(amountIssues);
        setType(type);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(edu.java.domain.jooq.generation2.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setLinkName(value.getLinkName());
            setLastCheck(value.getLastCheck());
            setLastUpdate(value.getLastUpdate());
            setLastCommit(value.getLastCommit());
            setAmountIssues(value.getAmountIssues());
            setType(value.getType());
            resetChangedOnNotNull();
        }
    }
}
